--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: sql-app
      tier: backend
      track: stable
  template: 
    metadata: 
      labels: 
        app: sql-app
        tier: backend
        track: stable
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MYSQL_ROOT_PASSWORD
              value: rootuser
          image: "harirharan95/mydockerrepo:mysqlimage"
          imagePullPolicy: Always
          name: mysql-container
          ports: 
            - 
              containerPort: 3306
              name: http

